### ISSUE TITLE
Each event being sent indefinitely

### ISSUE THREAD

**Issue by fj39** [germanrcuriel/assetto-corsa-server-udp2ws#33]
Hello! Thanks for writing this package, it's actually super useful.
I've got an issue with it though, which is that every single event is seemingly sent repeatedly and forever (well until the connection closes).

For example `session_info` and `new_session` are being sent constantly.
If I'm listening to socket.on('chat', { console.log(data) }), and send a message in the game's chat, the browser will log it forever, like the event is emitted constantly, not just once.

Wondering if this is a problem with my configuration somewhere, or actually an issue with the socket server?

I'm using ACSM to launch udp2ws as a plugin and the ac server and events are being emitted over ws, so it's a start!

Thanks for the help!

**Comment by germanrcuriel** [comment]
Hello! Thanks for the nice words 😄 

ACSM is messing a bit with the UDP communication when doing it that way. 

This project is not being actively maintained because I don't do any sim-racing nowadays but... when I used this application I was always running udp2ws as a separate process using Assetto Corsa Server ports and then connecting ACSM to the proxied udp2ws ports.

**Comment by fj39** [comment]
Thanks for getting back to me, can confirm that when launching through terminal rather than hooking udp2ws into ACSM, everything now works as expected, which is wonderful. Thanks for building this, it's super helpful!

**Comment by germanrcuriel** [comment]
I'm glad to hear that! Thanks to you!
